### ISSUE TITLE
Maybe include space char in first-time mention of array brackets?

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/phase-0-working-with-data-structures-intro#4] opened 2022-04-06 19:14 UTC
### Canvas Link

https://learning.flatironschool.com/courses/5506/pages/introduction-to-working-with-data-structures?module_item_id=371057

### Concern

In this first written description of the "[ ]" characters used for an array:

that should go in the Array, wrapped in [].

I would guess that someone seeing a red box (i.e. the "[]" thing) might not pick up on the fact that these are left-bracket and right-bracket characters. Maybe they will look at the model code:

const theBeatles = [

and get the hint, but for many, it will probably take 20-120 seconds of puzzling before they finally figure out that this is [, ]. Is this necessary for learning? i.e. won't there be plenty of other puzzles to solve?

### Suggested Changes

How about including a space char between [ and ] in the following so that the thing doesn't look like a red box, causing WTF for a first-time viewer, e.g.:

that should go in the Array, wrapped in [ ].

instead of:
that should go in the Array, wrapped in [].

**Comment by AlveeM** [comment] 2022-04-08 14:50
Hi Brigham, thanks for submitting this issue.

Students are expected to try out the codes as they read through the lessons. Most simple JavaScript code can be run in the [browser console](https://appuals.com/open-browser-console/). This should give them the opportunity to clarify any confusion regarding the `[]` brackets.

Additionally, the issue is being caused by Canvas' rendering of the text rather than the text itself. For example, if you read the code on GitHub there's sufficient spacing.

I'll look into Canvas rendering to see if we can make it better. For now, I'm going to keep the lesson as it is and close the issue since the problem isn't with the code in the lesson.

Thanks again for bringing up this issue and helping us improve our curriculum! Happy learning!

**Closed as completed by AlveeM** 2022-04-08 14:50 UTC
Labels: se curriculum
